{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Model: \"autoencoder\"\n",
      "_________________________________________________________________\n",
      "Layer (type)                 Output Shape              Param #   \n",
      "=================================================================\n",
      "input_2 (InputLayer)         [(None, 8, 8, 1)]         0         \n",
      "_________________________________________________________________\n",
      "encoder (Functional)         (None, 16)                2144      \n",
      "_________________________________________________________________\n",
      "decoder (Functional)         (None, 8, 8, 1)           2833      \n",
      "=================================================================\n",
      "Total params: 4,977\n",
      "Trainable params: 4,977\n",
      "Non-trainable params: 0\n",
      "_________________________________________________________________\n",
      "input_2 InputLayer {'batch_input_shape': (None, 8, 8, 1), 'dtype': 'float32', 'sparse': False, 'ragged': False, 'name': 'input_2'}\n",
      "input_2 InputLayer {'batch_input_shape': (None, 8, 8, 1), 'dtype': 'float32', 'sparse': False, 'ragged': False, 'name': 'input_2'}\n",
      "conv2d_1 Conv2D {'name': 'conv2d_1', 'trainable': True, 'dtype': 'float32', 'filters': 8, 'kernel_size': (3, 3), 'strides': (2, 2), 'padding': 'same', 'data_format': 'channels_last', 'dilation_rate': (1, 1), 'groups': 1, 'activation': 'relu', 'use_bias': True, 'kernel_initializer': {'class_name': 'GlorotUniform', 'config': {'seed': None}}, 'bias_initializer': {'class_name': 'Zeros', 'config': {}}, 'kernel_regularizer': None, 'bias_regularizer': None, 'activity_regularizer': None, 'kernel_constraint': None, 'bias_constraint': None}\n",
      "flatten_1 Flatten {'name': 'flatten_1', 'trainable': True, 'dtype': 'float32', 'data_format': 'channels_last'}\n",
      "encoded_vector Dense {'name': 'encoded_vector', 'trainable': True, 'dtype': 'float32', 'units': 16, 'activation': 'relu', 'use_bias': True, 'kernel_initializer': {'class_name': 'GlorotUniform', 'config': {'seed': None}}, 'bias_initializer': {'class_name': 'Zeros', 'config': {}}, 'kernel_regularizer': None, 'bias_regularizer': None, 'activity_regularizer': None, 'kernel_constraint': None, 'bias_constraint': None}\n",
      "decoder_input InputLayer {'batch_input_shape': (None, 16), 'dtype': 'float32', 'sparse': False, 'ragged': False, 'name': 'decoder_input'}\n",
      "dense_1 Dense {'name': 'dense_1', 'trainable': True, 'dtype': 'float32', 'units': 128, 'activation': 'relu', 'use_bias': True, 'kernel_initializer': {'class_name': 'GlorotUniform', 'config': {'seed': None}}, 'bias_initializer': {'class_name': 'Zeros', 'config': {}}, 'kernel_regularizer': None, 'bias_regularizer': None, 'activity_regularizer': None, 'kernel_constraint': None, 'bias_constraint': None}\n",
      "reshape_1 Reshape {'name': 'reshape_1', 'trainable': True, 'dtype': 'float32', 'target_shape': (4, 4, 8)}\n",
      "conv2d_transpose_2 Conv2DTranspose {'name': 'conv2d_transpose_2', 'trainable': True, 'dtype': 'float32', 'filters': 8, 'kernel_size': (3, 3), 'strides': (2, 2), 'padding': 'same', 'data_format': 'channels_last', 'dilation_rate': (1, 1), 'groups': 1, 'activation': 'relu', 'use_bias': True, 'kernel_initializer': {'class_name': 'GlorotUniform', 'config': {'seed': None}}, 'bias_initializer': {'class_name': 'Zeros', 'config': {}}, 'kernel_regularizer': None, 'bias_regularizer': None, 'activity_regularizer': None, 'kernel_constraint': None, 'bias_constraint': None, 'output_padding': None}\n",
      "conv2d_transpose_3 Conv2DTranspose {'name': 'conv2d_transpose_3', 'trainable': True, 'dtype': 'float32', 'filters': 1, 'kernel_size': (3, 3), 'strides': (1, 1), 'padding': 'same', 'data_format': 'channels_last', 'dilation_rate': (1, 1), 'groups': 1, 'activation': 'linear', 'use_bias': True, 'kernel_initializer': {'class_name': 'GlorotUniform', 'config': {'seed': None}}, 'bias_initializer': {'class_name': 'Zeros', 'config': {}}, 'kernel_regularizer': None, 'bias_regularizer': None, 'activity_regularizer': None, 'kernel_constraint': None, 'bias_constraint': None, 'output_padding': None}\n",
      "decoder_output Activation {'name': 'decoder_output', 'trainable': True, 'dtype': 'float32', 'activation': 'sigmoid'}\n"
     ]
    }
   ],
   "source": [
    "import qkeras\n",
    "import tensorflow\n",
    "from tensorflow.keras.models import model_from_json\n",
    "from qkeras.utils import _add_supported_quantized_objects\n",
    "from tensorflow.keras.layers import Input\n",
    "co = {}\n",
    "_add_supported_quantized_objects(co)\n",
    "\n",
    "def load_model(file_path):\n",
    "    return tensorflow.keras.models.load_model(file_path, custom_objects=co)\n",
    "\n",
    "json_file = open('/home/rsshenoy/EMD_Loss/Nov10_8x8_c8_S2.json', 'r')\n",
    "loaded_model_json = json_file.read()\n",
    "json_file.close()\n",
    "model = model_from_json(loaded_model_json)\n",
    "model.load_weights('/home/rsshenoy/EMD_Loss/Nov10_8x8_c8_S2.hdf5') \n",
    "model.summary()\n",
    "\n",
    "input_layer = None\n",
    "output_layer = None\n",
    "\n",
    "for layer0 in model.layers:\n",
    "    if hasattr(layer0,'layers'):\n",
    "        for layer1 in layer0.layers:\n",
    "            print(layer1.name, layer1.__class__.__name__, layer1.get_config())\n",
    "    else:\n",
    "        print(layer0.name, layer0.__class__.__name__, layer0.get_config())"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "2021-05-19 17:29:29.404279: W tensorflow/stream_executor/platform/default/dso_loader.cc:60] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/local/nvidia/lib64:/usr/local/cuda/lib64\n",
      "2021-05-19 17:29:29.404341: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.\n",
      "2021-05-19 17:29:34.330255: I tensorflow/compiler/jit/xla_cpu_device.cc:41] Not creating XLA devices, tf_xla_enable_xla_devices not set\n",
      "2021-05-19 17:29:34.332536: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcuda.so.1\n",
      "2021-05-19 17:29:34.395703: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1720] Found device 0 with properties: \n",
      "pciBusID: 0000:89:00.0 name: GeForce GTX 1080 Ti computeCapability: 6.1\n",
      "coreClock: 1.582GHz coreCount: 28 deviceMemorySize: 10.92GiB deviceMemoryBandwidth: 451.17GiB/s\n",
      "2021-05-19 17:29:34.395882: W tensorflow/stream_executor/platform/default/dso_loader.cc:60] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/local/nvidia/lib64:/usr/local/cuda/lib64\n",
      "2021-05-19 17:29:34.395983: W tensorflow/stream_executor/platform/default/dso_loader.cc:60] Could not load dynamic library 'libcublas.so.11'; dlerror: libcublas.so.11: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/local/nvidia/lib64:/usr/local/cuda/lib64\n",
      "2021-05-19 17:29:34.396074: W tensorflow/stream_executor/platform/default/dso_loader.cc:60] Could not load dynamic library 'libcublasLt.so.11'; dlerror: libcublasLt.so.11: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/local/nvidia/lib64:/usr/local/cuda/lib64\n",
      "2021-05-19 17:29:34.396161: W tensorflow/stream_executor/platform/default/dso_loader.cc:60] Could not load dynamic library 'libcufft.so.10'; dlerror: libcufft.so.10: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/local/nvidia/lib64:/usr/local/cuda/lib64\n",
      "2021-05-19 17:29:34.396247: W tensorflow/stream_executor/platform/default/dso_loader.cc:60] Could not load dynamic library 'libcurand.so.10'; dlerror: libcurand.so.10: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/local/nvidia/lib64:/usr/local/cuda/lib64\n",
      "2021-05-19 17:29:34.396334: W tensorflow/stream_executor/platform/default/dso_loader.cc:60] Could not load dynamic library 'libcusolver.so.10'; dlerror: libcusolver.so.10: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/local/nvidia/lib64:/usr/local/cuda/lib64\n",
      "2021-05-19 17:29:34.396420: W tensorflow/stream_executor/platform/default/dso_loader.cc:60] Could not load dynamic library 'libcusparse.so.11'; dlerror: libcusparse.so.11: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/local/nvidia/lib64:/usr/local/cuda/lib64\n",
      "2021-05-19 17:29:34.396509: W tensorflow/stream_executor/platform/default/dso_loader.cc:60] Could not load dynamic library 'libcudnn.so.8'; dlerror: libcudnn.so.8: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/local/nvidia/lib64:/usr/local/cuda/lib64\n",
      "2021-05-19 17:29:34.396531: W tensorflow/core/common_runtime/gpu/gpu_device.cc:1757] Cannot dlopen some GPU libraries. Please make sure the missing libraries mentioned above are installed properly if you would like to use GPU. Follow the guide at https://www.tensorflow.org/install/gpu for how to download and setup the required libraries for your platform.\n",
      "Skipping registering GPU devices...\n",
      "2021-05-19 17:29:34.397025: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA\n",
      "To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.\n",
      "2021-05-19 17:29:34.399884: I tensorflow/compiler/jit/xla_gpu_device.cc:99] Not creating XLA devices, tf_xla_enable_xla_devices not set\n",
      "2021-05-19 17:29:34.399923: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1261] Device interconnect StreamExecutor with strength 1 edge matrix:\n",
      "2021-05-19 17:29:34.399934: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1267]      \n",
      "2021-05-19 17:29:34.539579: I tensorflow/compiler/jit/xla_gpu_device.cc:99] Not creating XLA devices, tf_xla_enable_xla_devices not set\n",
      "2021-05-19 17:29:34.544334: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1720] Found device 0 with properties: \n",
      "pciBusID: 0000:89:00.0 name: GeForce GTX 1080 Ti computeCapability: 6.1\n",
      "coreClock: 1.582GHz coreCount: 28 deviceMemorySize: 10.92GiB deviceMemoryBandwidth: 451.17GiB/s\n",
      "2021-05-19 17:29:34.544560: W tensorflow/stream_executor/platform/default/dso_loader.cc:60] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/local/nvidia/lib64:/usr/local/cuda/lib64\n",
      "2021-05-19 17:29:34.544674: W tensorflow/stream_executor/platform/default/dso_loader.cc:60] Could not load dynamic library 'libcublas.so.11'; dlerror: libcublas.so.11: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/local/nvidia/lib64:/usr/local/cuda/lib64\n",
      "2021-05-19 17:29:34.544778: W tensorflow/stream_executor/platform/default/dso_loader.cc:60] Could not load dynamic library 'libcublasLt.so.11'; dlerror: libcublasLt.so.11: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/local/nvidia/lib64:/usr/local/cuda/lib64\n",
      "2021-05-19 17:29:34.544881: W tensorflow/stream_executor/platform/default/dso_loader.cc:60] Could not load dynamic library 'libcufft.so.10'; dlerror: libcufft.so.10: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/local/nvidia/lib64:/usr/local/cuda/lib64\n",
      "2021-05-19 17:29:34.544992: W tensorflow/stream_executor/platform/default/dso_loader.cc:60] Could not load dynamic library 'libcurand.so.10'; dlerror: libcurand.so.10: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/local/nvidia/lib64:/usr/local/cuda/lib64\n",
      "2021-05-19 17:29:34.545114: W tensorflow/stream_executor/platform/default/dso_loader.cc:60] Could not load dynamic library 'libcusolver.so.10'; dlerror: libcusolver.so.10: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/local/nvidia/lib64:/usr/local/cuda/lib64\n",
      "2021-05-19 17:29:34.545216: W tensorflow/stream_executor/platform/default/dso_loader.cc:60] Could not load dynamic library 'libcusparse.so.11'; dlerror: libcusparse.so.11: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/local/nvidia/lib64:/usr/local/cuda/lib64\n",
      "2021-05-19 17:29:34.545328: W tensorflow/stream_executor/platform/default/dso_loader.cc:60] Could not load dynamic library 'libcudnn.so.8'; dlerror: libcudnn.so.8: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/local/nvidia/lib64:/usr/local/cuda/lib64\n",
      "2021-05-19 17:29:34.545349: W tensorflow/core/common_runtime/gpu/gpu_device.cc:1757] Cannot dlopen some GPU libraries. Please make sure the missing libraries mentioned above are installed properly if you would like to use GPU. Follow the guide at https://www.tensorflow.org/install/gpu for how to download and setup the required libraries for your platform.\n",
      "Skipping registering GPU devices...\n",
      "2021-05-19 17:29:34.850554: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1261] Device interconnect StreamExecutor with strength 1 edge matrix:\n",
      "2021-05-19 17:29:34.850604: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1267]      0 \n",
      "2021-05-19 17:29:34.850620: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1280] 0:   N \n",
      "[name: \"/device:CPU:0\"\n",
      "device_type: \"CPU\"\n",
      "memory_limit: 268435456\n",
      "locality {\n",
      "}\n",
      "incarnation: 468955297213432636\n",
      "]\n",
      "Num GPUs Available:  0\n",
      "Is GPU available?  []\n",
      "input data shape: (490126, 48)\n",
      "Model: \"autoencoder\"\n",
      "_________________________________________________________________\n",
      "Layer (type)                 Output Shape              Param #   \n",
      "=================================================================\n",
      "input_2 (InputLayer)         [(None, 8, 8, 1)]         0         \n",
      "_________________________________________________________________\n",
      "encoder (Functional)         (None, 16)                2144      \n",
      "_________________________________________________________________\n",
      "decoder (Functional)         (None, 8, 8, 1)           2833      \n",
      "=================================================================\n",
      "Total params: 4,977\n",
      "Trainable params: 4,977\n",
      "Non-trainable params: 0\n",
      "_________________________________________________________________\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Saving ./occ_all.pdf\n",
      "Saving ./occ_1MT.pdf\n",
      "Saving ./maxQ_all.pdf\n",
      "Saving ./sumQ_all.pdf\n",
      "training shape (392101, 8, 8, 1)\n",
      "validation shape (98025, 8, 8, 1)\n",
      "2021-05-19 17:29:44.517240: I tensorflow/compiler/mlir/mlir_graph_optimization_pass.cc:116] None of the MLIR optimization passes are enabled (registered 2)\n",
      "2021-05-19 17:29:44.517888: I tensorflow/core/platform/profile_utils/cpu_utils.cc:112] CPU Frequency: 2199835000 Hz\n",
      "WARNING:tensorflow:AutoGraph could not transform <function Model.make_train_function.<locals>.train_function at 0x7fa5a40bf0e0> and will run it as-is.\n",
      "Please report this to the TensorFlow team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output.\n",
      "Cause: 'arguments' object has no attribute 'posonlyargs'\n",
      "To silence this warning, decorate the function with @tf.autograph.experimental.do_not_convert\n",
      "WARNING:tensorflow:AutoGraph could not transform <function emd_loss at 0x7fa610375290> and will run it as-is.\n",
      "Please report this to the TensorFlow team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output.\n",
      "Cause: module 'gast' has no attribute 'Constant'\n",
      "To silence this warning, decorate the function with @tf.autograph.experimental.do_not_convert\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/rsshenoy/.local/lib/python3.7/site-packages/tensorflow/python/autograph/impl/api.py\", line 447, in converted_call\n",
      "    converted_f = _convert_actual(target_entity, program_ctx)\n",
      "  File \"/home/rsshenoy/.local/lib/python3.7/site-packages/tensorflow/python/autograph/impl/api.py\", line 284, in _convert_actual\n",
      "    transformed, module, source_map = _TRANSPILER.transform(entity, program_ctx)\n",
      "  File \"/home/rsshenoy/.local/lib/python3.7/site-packages/tensorflow/python/autograph/pyct/transpiler.py\", line 286, in transform\n",
      "    return self.transform_function(obj, user_context)\n",
      "  File \"/home/rsshenoy/.local/lib/python3.7/site-packages/tensorflow/python/autograph/pyct/transpiler.py\", line 470, in transform_function\n",
      "    nodes, ctx = super(PyToPy, self).transform_function(fn, user_context)\n",
      "  File \"/home/rsshenoy/.local/lib/python3.7/site-packages/tensorflow/python/autograph/pyct/transpiler.py\", line 363, in transform_function\n",
      "    result = self.transform_ast(node, context)\n",
      "  File \"/home/rsshenoy/.local/lib/python3.7/site-packages/tensorflow/python/autograph/impl/api.py\", line 252, in transform_ast\n",
      "    node = self.initial_analysis(node, ctx)\n",
      "  File \"/home/rsshenoy/.local/lib/python3.7/site-packages/tensorflow/python/autograph/impl/api.py\", line 240, in initial_analysis\n",
      "    node = activity.resolve(node, ctx, None)\n",
      "  File \"/home/rsshenoy/.local/lib/python3.7/site-packages/tensorflow/python/autograph/pyct/static_analysis/activity.py\", line 709, in resolve\n",
      "    return ActivityAnalyzer(context, parent_scope).visit(node)\n",
      "  File \"/home/rsshenoy/.local/lib/python3.7/site-packages/tensorflow/python/autograph/pyct/transformer.py\", line 445, in visit\n",
      "    result = super(Base, self).visit(node)\n",
      "  File \"/opt/conda/lib/python3.7/ast.py\", line 271, in visit\n",
      "    return visitor(node)\n",
      "  File \"/home/rsshenoy/.local/lib/python3.7/site-packages/tensorflow/python/autograph/pyct/static_analysis/activity.py\", line 579, in visit_FunctionDef\n",
      "    node = self._visit_arg_annotations(node)\n",
      "  File \"/home/rsshenoy/.local/lib/python3.7/site-packages/tensorflow/python/autograph/pyct/static_analysis/activity.py\", line 555, in _visit_arg_annotations\n",
      "    node = self._visit_arg_declarations(node)\n",
      "  File \"/home/rsshenoy/.local/lib/python3.7/site-packages/tensorflow/python/autograph/pyct/static_analysis/activity.py\", line 560, in _visit_arg_declarations\n",
      "    node.args.posonlyargs = self._visit_node_list(node.args.posonlyargs)\n",
      "AttributeError: 'arguments' object has no attribute 'posonlyargs'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/rsshenoy/.local/lib/python3.7/site-packages/tensorflow/python/autograph/impl/api.py\", line 447, in converted_call\n",
      "    converted_f = _convert_actual(target_entity, program_ctx)\n",
      "  File \"/home/rsshenoy/.local/lib/python3.7/site-packages/tensorflow/python/autograph/impl/api.py\", line 284, in _convert_actual\n",
      "    transformed, module, source_map = _TRANSPILER.transform(entity, program_ctx)\n",
      "  File \"/home/rsshenoy/.local/lib/python3.7/site-packages/tensorflow/python/autograph/pyct/transpiler.py\", line 286, in transform\n",
      "    return self.transform_function(obj, user_context)\n",
      "  File \"/home/rsshenoy/.local/lib/python3.7/site-packages/tensorflow/python/autograph/pyct/transpiler.py\", line 470, in transform_function\n",
      "    nodes, ctx = super(PyToPy, self).transform_function(fn, user_context)\n",
      "  File \"/home/rsshenoy/.local/lib/python3.7/site-packages/tensorflow/python/autograph/pyct/transpiler.py\", line 363, in transform_function\n",
      "    result = self.transform_ast(node, context)\n",
      "  File \"/home/rsshenoy/.local/lib/python3.7/site-packages/tensorflow/python/autograph/impl/api.py\", line 252, in transform_ast\n",
      "    node = self.initial_analysis(node, ctx)\n",
      "  File \"/home/rsshenoy/.local/lib/python3.7/site-packages/tensorflow/python/autograph/impl/api.py\", line 239, in initial_analysis\n",
      "    node = qual_names.resolve(node)\n",
      "  File \"/home/rsshenoy/.local/lib/python3.7/site-packages/tensorflow/python/autograph/pyct/qual_names.py\", line 252, in resolve\n",
      "    return QnResolver().visit(node)\n",
      "  File \"/opt/conda/lib/python3.7/ast.py\", line 271, in visit\n",
      "    return visitor(node)\n",
      "  File \"/opt/conda/lib/python3.7/ast.py\", line 326, in generic_visit\n",
      "    value = self.visit(value)\n",
      "  File \"/opt/conda/lib/python3.7/ast.py\", line 271, in visit\n",
      "    return visitor(node)\n",
      "  File \"/opt/conda/lib/python3.7/ast.py\", line 326, in generic_visit\n",
      "    value = self.visit(value)\n",
      "  File \"/opt/conda/lib/python3.7/ast.py\", line 271, in visit\n",
      "    return visitor(node)\n",
      "  File \"/opt/conda/lib/python3.7/ast.py\", line 326, in generic_visit\n",
      "    value = self.visit(value)\n",
      "  File \"/opt/conda/lib/python3.7/ast.py\", line 271, in visit\n",
      "    return visitor(node)\n",
      "  File \"/home/rsshenoy/.local/lib/python3.7/site-packages/tensorflow/python/autograph/pyct/qual_names.py\", line 230, in visit_Subscript\n",
      "    node = self.generic_visit(node)\n",
      "  File \"/opt/conda/lib/python3.7/ast.py\", line 335, in generic_visit\n",
      "    new_node = self.visit(old_value)\n",
      "  File \"/opt/conda/lib/python3.7/ast.py\", line 271, in visit\n",
      "    return visitor(node)\n",
      "  File \"/opt/conda/lib/python3.7/ast.py\", line 335, in generic_visit\n",
      "    new_node = self.visit(old_value)\n",
      "  File \"/opt/conda/lib/python3.7/ast.py\", line 271, in visit\n",
      "    return visitor(node)\n",
      "  File \"/opt/conda/lib/python3.7/ast.py\", line 326, in generic_visit\n",
      "    value = self.visit(value)\n",
      "  File \"/opt/conda/lib/python3.7/ast.py\", line 271, in visit\n",
      "    return visitor(node)\n",
      "  File \"/home/rsshenoy/.local/lib/python3.7/site-packages/tensorflow/python/autograph/pyct/qual_names.py\", line 236, in visit_Subscript\n",
      "    if isinstance(s.value, gast.Constant):\n",
      "AttributeError: module 'gast' has no attribute 'Constant'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"train1.py\", line 1168, in <module>\n",
      "    trainCNN(options,args)\n",
      "  File \"train1.py\", line 1085, in trainCNN\n",
      "    history = train(model,train_input,train_input,val_input,name=model_name,n_epochs = options.epochs,)\n",
      "  File \"train1.py\", line 275, in train\n",
      "    callbacks=[es]\n",
      "  File \"/home/rsshenoy/.local/lib/python3.7/site-packages/tensorflow/python/keras/engine/training.py\", line 1100, in fit\n",
      "    tmp_logs = self.train_function(iterator)\n",
      "  File \"/home/rsshenoy/.local/lib/python3.7/site-packages/tensorflow/python/eager/def_function.py\", line 828, in __call__\n",
      "    result = self._call(*args, **kwds)\n",
      "  File \"/home/rsshenoy/.local/lib/python3.7/site-packages/tensorflow/python/eager/def_function.py\", line 871, in _call\n",
      "    self._initialize(args, kwds, add_initializers_to=initializers)\n",
      "  File \"/home/rsshenoy/.local/lib/python3.7/site-packages/tensorflow/python/eager/def_function.py\", line 726, in _initialize\n",
      "    *args, **kwds))\n",
      "  File \"/home/rsshenoy/.local/lib/python3.7/site-packages/tensorflow/python/eager/function.py\", line 2969, in _get_concrete_function_internal_garbage_collected\n",
      "    graph_function, _ = self._maybe_define_function(args, kwargs)\n",
      "  File \"/home/rsshenoy/.local/lib/python3.7/site-packages/tensorflow/python/eager/function.py\", line 3361, in _maybe_define_function\n",
      "    graph_function = self._create_graph_function(args, kwargs)\n",
      "  File \"/home/rsshenoy/.local/lib/python3.7/site-packages/tensorflow/python/eager/function.py\", line 3206, in _create_graph_function\n",
      "    capture_by_value=self._capture_by_value),\n",
      "  File \"/home/rsshenoy/.local/lib/python3.7/site-packages/tensorflow/python/framework/func_graph.py\", line 990, in func_graph_from_py_func\n",
      "    func_outputs = python_func(*func_args, **func_kwargs)\n",
      "  File \"/home/rsshenoy/.local/lib/python3.7/site-packages/tensorflow/python/eager/def_function.py\", line 634, in wrapped_fn\n",
      "    out = weak_wrapped_fn().__wrapped__(*args, **kwds)\n",
      "  File \"/home/rsshenoy/.local/lib/python3.7/site-packages/tensorflow/python/framework/func_graph.py\", line 973, in wrapper\n",
      "    user_requested=True,\n",
      "  File \"/home/rsshenoy/.local/lib/python3.7/site-packages/tensorflow/python/autograph/impl/api.py\", line 454, in converted_call\n",
      "    return _fall_back_unconverted(f, args, kwargs, options, e)\n",
      "  File \"/home/rsshenoy/.local/lib/python3.7/site-packages/tensorflow/python/autograph/impl/api.py\", line 501, in _fall_back_unconverted\n",
      "    return _call_unconverted(f, args, kwargs, options)\n",
      "  File \"/home/rsshenoy/.local/lib/python3.7/site-packages/tensorflow/python/autograph/impl/api.py\", line 478, in _call_unconverted\n",
      "    return f(*args, **kwargs)\n",
      "  File \"/home/rsshenoy/.local/lib/python3.7/site-packages/tensorflow/python/keras/engine/training.py\", line 805, in train_function\n",
      "    return step_function(self, iterator)\n",
      "  File \"/home/rsshenoy/.local/lib/python3.7/site-packages/tensorflow/python/keras/engine/training.py\", line 795, in step_function\n",
      "    outputs = model.distribute_strategy.run(run_step, args=(data,))\n",
      "  File \"/home/rsshenoy/.local/lib/python3.7/site-packages/tensorflow/python/distribute/distribute_lib.py\", line 1259, in run\n",
      "    return self._extended.call_for_each_replica(fn, args=args, kwargs=kwargs)\n",
      "  File \"/home/rsshenoy/.local/lib/python3.7/site-packages/tensorflow/python/distribute/distribute_lib.py\", line 2730, in call_for_each_replica\n",
      "    return self._call_for_each_replica(fn, args, kwargs)\n",
      "  File \"/home/rsshenoy/.local/lib/python3.7/site-packages/tensorflow/python/distribute/distribute_lib.py\", line 3417, in _call_for_each_replica\n",
      "    return fn(*args, **kwargs)\n",
      "  File \"/home/rsshenoy/.local/lib/python3.7/site-packages/tensorflow/python/autograph/impl/api.py\", line 667, in wrapper\n",
      "    return converted_call(f, args, kwargs, options=options)\n",
      "  File \"/home/rsshenoy/.local/lib/python3.7/site-packages/tensorflow/python/autograph/impl/api.py\", line 396, in converted_call\n",
      "    return _call_unconverted(f, args, kwargs, options)\n",
      "  File \"/home/rsshenoy/.local/lib/python3.7/site-packages/tensorflow/python/autograph/impl/api.py\", line 478, in _call_unconverted\n",
      "    return f(*args, **kwargs)\n",
      "  File \"/home/rsshenoy/.local/lib/python3.7/site-packages/tensorflow/python/keras/engine/training.py\", line 788, in run_step\n",
      "    outputs = model.train_step(data)\n",
      "  File \"/home/rsshenoy/.local/lib/python3.7/site-packages/tensorflow/python/keras/engine/training.py\", line 756, in train_step\n",
      "    y, y_pred, sample_weight, regularization_losses=self.losses)\n",
      "  File \"/home/rsshenoy/.local/lib/python3.7/site-packages/tensorflow/python/keras/engine/compile_utils.py\", line 203, in __call__\n",
      "    loss_value = loss_obj(y_t, y_p, sample_weight=sw)\n",
      "  File \"/home/rsshenoy/.local/lib/python3.7/site-packages/tensorflow/python/keras/losses.py\", line 152, in __call__\n",
      "    losses = call_fn(y_true, y_pred)\n",
      "  File \"/home/rsshenoy/.local/lib/python3.7/site-packages/tensorflow/python/autograph/impl/api.py\", line 667, in wrapper\n",
      "    return converted_call(f, args, kwargs, options=options)\n",
      "  File \"/home/rsshenoy/.local/lib/python3.7/site-packages/tensorflow/python/autograph/impl/api.py\", line 396, in converted_call\n",
      "    return _call_unconverted(f, args, kwargs, options)\n",
      "  File \"/home/rsshenoy/.local/lib/python3.7/site-packages/tensorflow/python/autograph/impl/api.py\", line 478, in _call_unconverted\n",
      "    return f(*args, **kwargs)\n",
      "  File \"/home/rsshenoy/.local/lib/python3.7/site-packages/tensorflow/python/keras/losses.py\", line 256, in call\n",
      "    return ag_fn(y_true, y_pred, **self._fn_kwargs)\n",
      "  File \"/home/rsshenoy/.local/lib/python3.7/site-packages/tensorflow/python/autograph/impl/api.py\", line 667, in wrapper\n",
      "    return converted_call(f, args, kwargs, options=options)\n",
      "  File \"/home/rsshenoy/.local/lib/python3.7/site-packages/tensorflow/python/autograph/impl/api.py\", line 454, in converted_call\n",
      "    return _fall_back_unconverted(f, args, kwargs, options, e)\n",
      "  File \"/home/rsshenoy/.local/lib/python3.7/site-packages/tensorflow/python/autograph/impl/api.py\", line 501, in _fall_back_unconverted\n",
      "    return _call_unconverted(f, args, kwargs, options)\n",
      "  File \"/home/rsshenoy/.local/lib/python3.7/site-packages/tensorflow/python/autograph/impl/api.py\", line 478, in _call_unconverted\n",
      "    return f(*args, **kwargs)\n",
      "  File \"/home/rsshenoy/EMD_Loss/emdloss.py\", line 90, in emd_loss\n",
      "    print(tf.shape(y_true).numpy())\n",
      "AttributeError: 'Tensor' object has no attribute 'numpy'\n"
     ]
    }
   ],
   "source": [
    "!python train1.py -i /home/rsshenoy/EMD_Loss/data/nElinks_5/ -o ./testemd/ --epoch 1 --AEonly 1 --nELinks 5"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 7,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Num GPUs Available:  0\n"
     ]
    }
   ],
   "source": [
    "import tensorflow as tf\n",
    "print(\"Num GPUs Available: \", len(tf.config.experimental.list_physical_devices('GPU')))"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.7.6"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 4
}
